### ISSUE TITLE
doesn't start for bluetooth mouse

### ISSUE THREAD

**Issue by bam80** [kyokenn/rogdrv#37]
For Pugio 2 connected with BT mode:
```
$ rogdrv
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/dist-packages/rogdrv-0.3.0-py3.9.egg/rog/__main__.py", line 65, in run
    e = self._device.next_event()
AttributeError: 'NoneType' object has no attribute 'next_event'
Traceback (most recent call last):
  File "/usr/local/bin/rogdrv", line 33, in <module>
    sys.exit(load_entry_point('rogdrv==0.3.0', 'console_scripts', 'rogdrv')())
  File "/usr/local/lib/python3.9/dist-packages/rogdrv-0.3.0-py3.9.egg/rog/__main__.py", line 393, in rogdrv
    gtk3_main(app.device)
  File "/usr/local/lib/python3.9/dist-packages/rogdrv-0.3.0-py3.9.egg/rog/ui/__init__.py", line 49, in gtk3_main
    if not device.profiles:
AttributeError: 'NoneType' object has no attribute 'profiles'

**Comment by kyokenn** [comment]
Bluetooth is unsupported by hardware. You can confirm it by checking ```dmesg```
If you don't see "Consumer Control" interface in ```dmesg``` when connecting mouse with BT, then it can't be configured over BT.

**Comment by bam80** [comment]
I don't see "Consumer Control" interface in dmesg, closing. Thanks.
