### ISSUE TITLE
I need support for this mouse

### ISSUE THREAD

**Issue by Graval504** [kyokenn/rogdrv#39]
Sorry for posting Issue again
I bought rog strix impact II electro punk and I use this on my desktop, so i installed everything  I need on my desktop(Manjaro Linux)

but rogdrv can't find my mouse
~~~
[graval504@manjarograval ~]$ rogdrv
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/site-packages/rogdrv-0.3.0-py3.10.egg/rog/__main__.py", line 65, in run
    e = self._device.next_event()
AttributeError: 'NoneType' object has no attribute 'next_event'
Traceback (most recent call last):
  File "/usr/bin/rogdrv", line 33, in <module>
    sys.exit(load_entry_point('rogdrv==0.3.0', 'console_scripts', 'rogdrv')())
  File "/usr/lib/python3.10/site-packages/rogdrv-0.3.0-py3.10.egg/rog/__main__.py", line 393, in rogdrv
    gtk3_main(app.device)
  File "/usr/lib/python3.10/site-packages/rogdrv-0.3.0-py3.10.egg/rog/ui/__init__.py", line 49, in gtk3_main
    if not device.profiles:
AttributeError: 'NoneType' object has no attribute 'profiles'
~~~

but I can find my mouse and its Consumer control in terminal(dmesg)
~~~
[graval504@manjarograval ~]$ sudo dmesg
[sudo] password for graval504: 
~~
[    4.897281] hid-generic 0003:0B05:1956.0005: hiddev98,hidraw4: USB HID v1.11 Device [ASUSTeK ROG STRIX IMPACT II ELECTRO PUNK] on usb-0000:28:00.3-3/input0
[    4.906067] input: ASUSTeK ROG STRIX IMPACT II ELECTRO PUNK as /devices/pci0000:00/0000:00:07.1/0000:28:00.3/usb3/3-3/3-3:1.1/0003:0B05:1956.0006/input/input26
[    4.906203] hid-generic 0003:0B05:1956.0006: input,hidraw5: USB HID v1.11 Mouse [ASUSTeK ROG STRIX IMPACT II ELECTRO PUNK] on usb-0000:28:00.3-3/input1
[    4.916521] input: ASUSTeK ROG STRIX IMPACT II ELECTRO PUNK Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:28:00.3/usb3/3-3/3-3:1.2/0003:0B05:1956.0007/input/input27
[    4.970155] input: ASUSTeK ROG STRIX IMPACT II ELECTRO PUNK System Control as /devices/pci0000:00/0000:00:07.1/0000:28:00.3/usb3/3-3/3-3:1.2/0003:0B05:1956.0007/input/input28
[    4.970210] input: ASUSTeK ROG STRIX IMPACT II ELECTRO PUNK Keyboard as /devices/pci0000:00/0000:00:07.1/0000:28:00.3/usb3/3-3/3-3:1.2/0003:0B05:1956.0007/input/input30
[    4.970297] hid-generic 0003:0B05:1956.0007: input,hiddev99,hidraw6: USB HID v1.11 Keyboard [ASUSTeK ROG STRIX IMPACT II ELECTRO PUNK] on usb-0000:28:00.3-3/input2
~~
~~~

Can this problem be solved?

**Comment by kyokenn** [comment]
I have added this mouse to the driver. You can check if it works.

**Comment by Graval504** [comment]
Thx!
