### ISSUE TITLE
ModuleNotFoundError: No module named 'hidapi'

### ISSUE THREAD

**Issue by dataprolet** [kyokenn/rogdrv#8]
I'm running 5.6.12-1-MANJARO and got the following installed:  
python 3.8.2-2  
python-hidapi 0.9.0.2-4  
python-cffi 1.14.0-2  
python-evdev 1.3.0-1  
libappindicator-gtk3 12.10.0-14  
  
When I run _rogdrv_ or _rogdrv-config_ I get the following error:  
```
Traceback (most recent call last):
  File "/usr/bin/rogdrv", line 11, in <module>
    load_entry_point('rogdrv==0.0.5', 'console_scripts', 'rogdrv')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/rogdrv-0.0.5-py3.8.egg/rogdrv/__main__.py", line 24, in <module>
    from .device import EventHandler, get_device
  File "/usr/lib/python3.8/site-packages/rogdrv-0.0.5-py3.8.egg/rogdrv/device.py", line 18, in <module>
    import hidapi
ModuleNotFoundError: No module named 'hidapi'
```

**Comment by kyokenn** [comment]
Make sure that you have installed python-hidapi for the python3, not python2. Sometimes the packages for python3 are called something like python3-hidapi, but it depends on linux distribution.
